targetURL: "http://127.0.0.1/index.html"
userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
selectors:
  cpu:  "<CSS Selector>"
  mem:  "<CSS Selector>"
  temp: "<CSS Selector>"
  2G:   "<CSS Selector>"
  5G:   "<CSS Selector>"
